<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <main>

        <form action="EJ6.php" method="post">

        <h3>Cada volante tendrá un valor de impresión de: $2.000<br>
        <br></br>
 Cada poster tendrá un valor de impresión de: $5.000 <br>
 <br></br>

 Y las tarjetas de presentación a $500 cada una.</h3>


            <label for="valor">Numero de volantes</label><input name="valor1" type="text" value="">
            <label for="valor1">Numero de impresion</label><input name="valor2" type="text" value="">
            <label for="valor2">Numero de tarjetas</label><input name="valor3" type="text" value="">
            <input type="submit" name="enviar" value="enviar" >

     

        </form>
    </main>
</body>
</html>